### ISSUE TITLE
Incorrect masking/padding behavior at edges?

### ISSUE THREAD

**Issue by josephrocca** [4rtemi5/imax#4]
Minimal reproduction: https://colab.research.google.com/gist/josephrocca/e2d841274665cc3c275634456e2531ec

```python
image = Image.new('RGBA', (2, 2), color=(0, 0, 0))
pixels = np.array(image)
print("Original:")
print(pixels)
pixels = transforms.apply_transform(pixels, transforms.flip(horizontal=True), mask_value=np.array([255, 255, 255, 255]))
print("Flipped:")
print(pixels)
```
Outputs:
```
Original:
[[[  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]]]
Flipped:
[[[255 255 255 255]
  [  0   0   0 255]]

 [[255 255 255 255]
  [255 255 255 255]]]
```

**Edit:** I originally thought that this issue only occurred for the `flip` transformation, but it occurs with other transformations too, including `scale`. Pixels of color `mask_value` are added around the edges of the image - though not all the way around, and the parts of the border that have the `mask_value` padding seem to vary.

**Comment by 4rtemi5** [comment]
Fixed after years of delay. Thanks for reporting!
