### ISSUE TITLE
Gradients are zero after applying any transform?

### ISSUE THREAD

**Issue by josephrocca** [4rtemi5/imax#5]
Here's a simple function that just takes an image, performs a "no-op" scaling transformation (though any value of `x_factor` and `y_factor` can be used to reproduce this issue), and returns the mean of all the pixels:
```python
def score(rc_rgba):
    transform = transforms.scale(x_factor=1, y_factor=1)
    rc_rgba = transforms.apply_transform(rc_rgba, transform, mask_value=np.array([255, 255, 255, 255]), bilinear=False)
    return rc_rgba.mean()
```
The gradient of the pixel values should be positive, but they're zero:
```python
image = Image.new('RGBA', size=(2, 2), color=(50, 100, 50))
rc_rgba = np.asarray(image).astype('float32')
print( score(rc_rgba) )
print( grad(score)(rc_rgba) )
```
```
219.6875
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
```
The same thing happens for all the other transformations that I've tested. If I remove the transformation, then the gradients are correct:
```
113.75
[[[0.0625 0.0625 0.0625 0.0625]
  [0.0625 0.0625 0.0625 0.0625]]

 [[0.0625 0.0625 0.0625 0.0625]
  [0.0625 0.0625 0.0625 0.0625]]]
```
(The score is now incorrect, but that's a separate issue: #4)

**Comment by 4rtemi5** [comment]
Hi @josephrocca ! Terribly sorry for the late reply! The problem with your issue is the `bilinear=False`.  Unfortunately the nearest neighbor implementation is not differentiable so you will not get gradients.

**Comment by 4rtemi5** [comment]
After looking into it again I was able to allow gradient coputation for both bilinear and nearest_neighbor samplers. Should be fixed now.
Sorry for taking so long to look into this.
